// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snhnmyfvgarmwnlreati.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuaG5teWZ2Z2FybXdubHJlYXRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4MDIyMjUsImV4cCI6MjA1MjM3ODIyNX0.9GROqebb4k6H2XzVd4T_2x6AHNDiEg-fJClxJ1teSWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);